datejust:
    pattern:  /
    defaults: { _controller: "Just2BackendBundle:DateJust:index" }

datejust_show:
    pattern:  /{id}/ver
    defaults: { _controller: "Just2BackendBundle:DateJust:show" }

datejust_new:
    pattern:  /nuevo
    defaults: { _controller: "Just2BackendBundle:DateJust:new" }

datejust_create:
    pattern:  /create
    defaults: { _controller: "Just2BackendBundle:DateJust:create" }
    requirements: { _method: post }

datejust_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "Just2BackendBundle:DateJust:edit" }

datejust_update:
    pattern:  /{id}/cambiar
    defaults: { _controller: "Just2BackendBundle:DateJust:update" }
    requirements: { _method: post }

datejust_delete:
    pattern:  /{id}/eliminar
    defaults: { _controller: "Just2BackendBundle:DateJust:delete" }
    requirements: { _method: post }
