reservation:
    pattern:  /
    defaults: { _controller: "Just2BackendBundle:Reservation:index" }

reservation_show:
    pattern:  /{id}/ver
    defaults: { _controller: "Just2BackendBundle:Reservation:show" }

reservation_new:
    pattern:  /nuevo
    defaults: { _controller: "Just2BackendBundle:Reservation:new" }

reservation_create:
    pattern:  /create
    defaults: { _controller: "Just2BackendBundle:Reservation:create" }
    requirements: { _method: post }

reservation_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "Just2BackendBundle:Reservation:edit" }

reservation_update:
    pattern:  /{id}/cambiar
    defaults: { _controller: "Just2BackendBundle:Reservation:update" }
    requirements: { _method: post }

reservation_delete:
    pattern:  /{id}/eliminar
    defaults: { _controller: "Just2BackendBundle:Reservation:delete" }
    requirements: { _method: post }
