security:
    encoders:
        JVJ\UserBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        
        

    providers:
        # Usuarios del frontend
        usuarios:
           entity: { class: JVJUserBundle:User,  }

    firewalls:
        usuario:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:       /logout
                target:     /           
            remember_me:
                key:        jvjusuario
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }      
#       - { path: ^/usuario/(login|identificar),         roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/usuario/new/*,  roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_NUEVO] }       
#        - { path: ^/usuario/*,         roles: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_NUEVO] } 
        - { path: ^/admin/*,         roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        