parameters:
#    just2_frontend.example.class: Just2\FrontendBundle\Example

services:
#    just2_frontend.example:
#        class: %just2_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
