venue_search:
    pattern:  /
    defaults: { _controller: Just2FrontendBundle:VenueJust:search}

venue_results:
    pattern:  /search
    defaults: { _controller: Just2FrontendBundle:VenueJust:show}