parameters:
#    just2_backend.example.class: Just2\BackendBundle\Example

services:
#    just2_backend.example:
#        class: %just2_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
