<?php

namespace Just2\BackendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VenueController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Just2\BackendBundle\Controller\VenueController();
        return $instance;
    }
}
