<?php

namespace Just2\FrontendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BidController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Just2\FrontendBundle\Controller\BidController();
        return $instance;
    }
}
