jvj_user_user:
    resource: "@JVJUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

usuario_login:
    pattern:  /login
    defaults: { _controller: JVJUserBundle:User:login }
    
usuario_registro:
    pattern:  /identificar
    defaults: { _controller: JVJUsuarioBundle:Default:registro }
# Ruta para la acción que comprueba el login del frontend
usuario_perfil:
    pattern:  /perfil
    defaults: { _controller: AutoFrontendBundle:Default:perfil }

usuario_login_check:
    pattern:   /login_check

# Ruta para la acción de logout de los usuarios del frontend extranet
usuario_logout:
    pattern:   /logout